apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: xfx-adapter-secrets
  namespace: xfx-adapter-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: xfx-adapter-secrets
    creationPolicy: Owner
    template:
      data:
        DATABASE_URL: "{{ .DATABASE_URL }}"
        REDIS_PASS: "{{ .REDIS_PASS }}"
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: xfx-adapter/dev
        property: DATABASE_URL
    - secretKey: REDIS_PASS
      remoteRef:
        key: xfx-adapter/dev
        property: REDIS_PASS
