apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: xfx-adapter-dev

resources:
  - ../../base
  - secretstore.yaml
  - externalsecret.yaml

namePrefix: dev-

images:
  - name: xfx-adapter
    newName: 730335471935.dkr.ecr.us-east-2.amazonaws.com/xfx-adapter
    newTag: dev

patches:
  - patch: |-
      - op: replace
        path: /metadata/name
        value: xfx-adapter-dev
    target:
      kind: Namespace
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: xfx-adapter
  - target:
      kind: ConfigMap
      name: xfx-adapter-config
    patch: |-
      - op: replace
        path: /data/ENV
        value: dev
      - op: replace
        path: /data/LOG_LEVEL
        value: debug
      - op: replace
        path: /data/XFX_POLL_INTERVAL
        value: 15s
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: xfx-dev.checker.finance
    target:
      kind: Ingress
      name: xfx-adapter
