apiVersion: v1
kind: Service
metadata:
  name: braza-adapter
  namespace: braza-adapter
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9020
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: braza-adapter
