apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: xfx-adapter
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-2:730335471935:certificate/9ea54c0a-96f0-4799-9cfd-0d3459ec94f9
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/target-group-attributes: slow_start.duration_seconds=30
spec:
  ingressClassName: alb
  rules:
    - host: xfx.checker.finance
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: xfx-adapter
                port:
                  number: 9030
