apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rio-adapter-secrets
  namespace: rio-adapter-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: rio-adapter-secrets
    creationPolicy: Owner
    template:
      data:
        DATABASE_URL: "{{ .DATABASE_URL }}"
        RIO_API_KEY: "{{ .RIO_API_KEY }}"
        REDIS_PASS: "{{ .REDIS_PASS }}"
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: rio-adapter/dev
        property: DATABASE_URL
    - secretKey: RIO_API_KEY
      remoteRef:
        key: rio-adapter/dev
        property: RIO_API_KEY
    - secretKey: REDIS_PASS
      remoteRef:
        key: rio-adapter/dev
        property: REDIS_PASS
