apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rio-adapter-dev

resources:
  - ../../base
  - secretstore.yaml
  - externalsecret.yaml

namePrefix: dev-

images:
  - name: rio-adapter
    newName: 730335471935.dkr.ecr.us-east-2.amazonaws.com/rio-adapter
    newTag: dev

patches:
  - patch: |-
      - op: replace
        path: /metadata/name
        value: rio-adapter-dev
    target:
      kind: Namespace
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: rio-adapter
  - target:
      kind: ConfigMap
      name: rio-adapter-config
    patch: |-
      - op: replace
        path: /data/ENV
        value: dev
      - op: replace
        path: /data/LOG_LEVEL
        value: debug
      - op: add
        path: /data/RIO_BASE_URL
        value: https://app.sandbox.rio.trade
      - op: add
        path: /data/RIO_API_KEY_SECRET
        value: rio/dev/api-key
      - op: add
        path: /data/AWS_REGION
        value: us-east-2
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: rio-dev.checker.finance
      - op: replace
        path: /metadata/annotations/external-dns.alpha.kubernetes.io~1hostname
        value: rio-dev.checker.finance.
    target:
      kind: Ingress
      name: rio-adapter
