apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: braza-adapter-secrets
  namespace: braza-adapter-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: braza-adapter-secrets
    creationPolicy: Owner
    template:
      data:
        DATABASE_URL: "{{ .DATABASE_URL }}"
        BRAZA_API_KEY: "{{ .BRAZA_API_KEY }}"
        REDIS_PASS: "{{ .REDIS_PASS }}"
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: braza-adapter/dev
        property: DATABASE_URL
    - secretKey: BRAZA_API_KEY
      remoteRef:
        key: braza-adapter/dev
        property: BRAZA_API_KEY
    - secretKey: REDIS_PASS
      remoteRef:
        key: braza-adapter/dev
        property: REDIS_PASS
