apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: braza-adapter-dev

resources:
  - ../../base
  - secretstore.yaml
  - externalsecret.yaml

namePrefix: dev-

images:
  - name: braza-adapter
    newName: 730335471935.dkr.ecr.us-east-2.amazonaws.com/braza-adapter
    newTag: dev

patches:
  - patch: |-
      - op: replace
        path: /metadata/name
        value: braza-adapter-dev
    target:
      kind: Namespace
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: braza-adapter
  - target:
      kind: ConfigMap
      name: braza-adapter-config
    patch: |-
      - op: replace
        path: /data/ENV
        value: dev
      - op: replace
        path: /data/LOG_LEVEL
        value: debug
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: braza-dev.checker.finance
      - op: replace
        path: /metadata/annotations/external-dns.alpha.kubernetes.io~1hostname
        value: braza-dev.checker.finance.
    target:
      kind: Ingress
      name: braza-adapter
