apiVersion: v1
kind: Service
metadata:
  name: rio-adapter
  namespace: rio-adapter
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9010
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: rio-adapter
